/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sustainability;

/**
 *
 * @author dell
 */
public class Link2 extends javax.swing.JFrame {

    /**
     * Creates new form Link2
     */
    public Link2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundLBL = new javax.swing.JPanel();
        gobackBTN = new javax.swing.JButton();
        titleLBL = new javax.swing.JLabel();
        label1LBL = new javax.swing.JLabel();
        Labe2LBL = new javax.swing.JLabel();
        textfield1TF = new javax.swing.JTextField();
        textfield2TF = new javax.swing.JTextField();
        iconLBL = new javax.swing.JLabel();
        label4LBL = new javax.swing.JLabel();
        textfield3TF = new javax.swing.JTextField();
        button1BTN = new javax.swing.JButton();
        button2BTN = new javax.swing.JButton();
        button3BTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ocean Cleanup Info | Harry");
        setResizable(false);

        backgroundLBL.setBackground(new java.awt.Color(0, 124, 186));

        gobackBTN.setBackground(new java.awt.Color(210, 231, 241));
        gobackBTN.setForeground(new java.awt.Color(148, 196, 228));
        gobackBTN.setText("Go Back");
        gobackBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackBTNActionPerformed(evt);
            }
        });

        titleLBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(210, 231, 241));
        titleLBL.setText("Ocean Cleanup Info");

        label1LBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label1LBL.setForeground(new java.awt.Color(210, 231, 241));
        label1LBL.setText("Debris Type");

        Labe2LBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Labe2LBL.setForeground(new java.awt.Color(210, 231, 241));
        Labe2LBL.setText("Location Found");

        textfield1TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfield1TFActionPerformed(evt);
            }
        });

        iconLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sustainability/oceanwave.png"))); // NOI18N

        label4LBL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label4LBL.setForeground(new java.awt.Color(210, 231, 241));
        label4LBL.setText("Quantity");

        button1BTN.setBackground(new java.awt.Color(210, 231, 241));
        button1BTN.setForeground(new java.awt.Color(148, 196, 228));
        button1BTN.setText("Add");

        button2BTN.setBackground(new java.awt.Color(210, 231, 241));
        button2BTN.setForeground(new java.awt.Color(148, 196, 228));
        button2BTN.setText("View");

        button3BTN.setBackground(new java.awt.Color(210, 231, 241));
        button3BTN.setForeground(new java.awt.Color(148, 196, 228));
        button3BTN.setText("Stats");

        javax.swing.GroupLayout backgroundLBLLayout = new javax.swing.GroupLayout(backgroundLBL);
        backgroundLBL.setLayout(backgroundLBLLayout);
        backgroundLBLLayout.setHorizontalGroup(
            backgroundLBLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLBLLayout.createSequentialGroup()
                .addGroup(backgroundLBLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLBLLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(backgroundLBLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button1BTN)
                            .addComponent(button2BTN)
                            .addComponent(button3BTN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgroundLBLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundLBLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(textfield3TF, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                .addComponent(textfield2TF)
                                .addGroup(backgroundLBLLayout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(label1LBL))
                                .addComponent(Labe2LBL)
                                .addComponent(label4LBL))
                            .addComponent(textfield1TF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(backgroundLBLLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(gobackBTN)
                        .addGap(18, 18, 18)
                        .addComponent(titleLBL)))
                .addGap(35, 35, 35))
        );
        backgroundLBLLayout.setVerticalGroup(
            backgroundLBLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLBLLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(backgroundLBLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLBL)
                    .addComponent(gobackBTN))
                .addGap(18, 18, 18)
                .addGroup(backgroundLBLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLBLLayout.createSequentialGroup()
                        .addComponent(label1LBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfield1TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Labe2LBL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textfield2TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(iconLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backgroundLBLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label4LBL)
                    .addComponent(button1BTN))
                .addGroup(backgroundLBLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLBLLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfield3TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundLBLLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(button2BTN)))
                .addGap(18, 18, 18)
                .addGroup(backgroundLBLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button3BTN)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gobackBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobackBTNActionPerformed
        // TODO add your handling code here:
        new LandingPageGUI().setVisible(true);  
        this.setVisible(false);
        System.out.println("closed");
        //this.setDefaultCloseOperation(MainAppGUI.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_gobackBTNActionPerformed

    private void textfield1TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfield1TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfield1TFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Link2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Link2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Link2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Link2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Link2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Labe2LBL;
    private javax.swing.JPanel backgroundLBL;
    private javax.swing.JButton button1BTN;
    private javax.swing.JButton button2BTN;
    private javax.swing.JButton button3BTN;
    private javax.swing.JButton gobackBTN;
    private javax.swing.JLabel iconLBL;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1LBL;
    private javax.swing.JLabel label4LBL;
    private javax.swing.JTextField textfield1TF;
    private javax.swing.JTextField textfield2TF;
    private javax.swing.JTextField textfield3TF;
    private javax.swing.JLabel titleLBL;
    // End of variables declaration//GEN-END:variables
}
